    name: Build Kivy Android App

    on:
      push:
        branches:
          - main # or your main branch

    jobs:
      build-android:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install --upgrade Cython
          - name: Build with Buildozer
            uses: ArtemSBulgakov/buildozer-action@v1
            id: buildozer
            with:
              repository_root: .github/workflows/
          - name: Upload Artifact
            uses: actions/upload-artifact@v2
            with:
              name: kivy-apk
              path: .github/workflows/bin/*.apk
